### PR TITLE
Prevent people from accidentially using an old container.

### PR DESCRIPTION
**Pull request by dehanj**

### CODE REVIEW

**Comment by quite** [comment]
I think we need to be careful with this. I have not had time think through this entirely, but I intentionally used a specific numbered tag for the tkey-builder image. Because our particular reproducability requirements, and rely on the exact toolchain being used and producing binaries with the *same* checksum. Using a `latest` tag makes this unpredictable. But yes, this does require updating this tag everywhere when we publish a new version. In documentation, in github CI yaml, and any scripts. But I *think* this is how we need to do things. 

I'd even go as far as removing the `latest` tag from the image repo! As well, even if we would use a `latest` tag, that would actually require user to explicitly pulling it to get any updated image from it, because podman/docker/etc does nothing special with a `latest` tag.

Related, for the coming tkey-qemu image, I think it does make sense to use a `latest` tag. At least if the image hash `tk-23.03.1` in its name, and the tag means an update to the image (like for QEMU updates, fixes to the TKey machine there, etc). We'd maintain that `latest` tag (pushing to it in addition to the next incremented tag number). Then `run-tkey-qemu` uses `latest` and has an option `-p` to try to re-pull it.

**Comment by quite** [comment]
In short, I think this PR should update to `:2` :)

**Comment by dehanj** [comment]
Makes sense. I agree with you, that we need to be careful. 

I see two things we might want to do then.
First, add a note about this here to clearly state the possibility of a new checksum when changing the toolchain (which I experienced when compiling with Clang-16). 

Secondly, can we sort of make a statement per version? Say we update the toolchain, we do check if the signer checksum changes in our CI. Would that hold for all applications? If so, we can state if the versions are "safe" to update to.

**Comment by quite** [comment]
> Secondly, can we make a statement per version? Say we update the toolchain, we do check if the signer checksum changes in our CI. Would that hold for all applications? If so, we can state if the versions are "safe" to update to. Thoughts?

Possibly we could do that, but I'd be very cautious. Bear in mind that our "toolchain", the `tkey-builder` image coming from this file: https://github.com/tillitis/tillitis-key1/blob/main/contrib/Dockerfile contains tools for building both bitstream (yosys), firmware (clang) and device apps (clang). The repos cloned and built should all be locked-down to commit/tag though

So if we update some tool there, and produce a new tkey-builder image version, and if also that builds everything without changing any checksum (that must not be changed), then we're good. This new image version could then be tagged and pushed, and all the references to for example `tkey-builder:2` should be changed to `tkey-builder:3`. But then you meant that we could actually publish a new version of tkey-builder image that breaks some checksum? That's what I'd say we must be cautious with. But at some point we just might have to! Then it must certainly be well-documented.

So a start is to document that this `tkey-builder:2` is the currently supported toolchain that will not break things. A toolchain installed on host/workstation will probably not give the same result.

**Comment by dehanj** [comment]
> But then you meant that we could actually publish a new version of tkey-builder image that breaks some checksum? 

Not that it is something that we should strive for, more that we might end up there for some reason. But I don't know what our default is; only publish new versions that does not break anything? If so, `latest` should be fine - even if I agree in our particular case it is better to be safe-than-sorry to prevent misstakes.

But, for now. I'll change this to 2 instead, and then we can give some longer thoughts to this further down the road.

**Review by quite — COMMENTED** [review]
Now I see that before your change, user is even told they can pull `:latest`. I'd say remove that completely and only show how to `run` with `:2`

And possibly a line about this toolchain image being the supported way to product a signer, fpga bitstream and firmware with the expected checksums?

**Comment by dehanj** [comment]
Changed both statements to point at version 2. Ready for review.

**Comment by dehanj** [comment]
Not relevant anymore.

**Pull request closed without merging**
